object Form1: TForm1
  Left = 0
  Top = 0
  Caption = 'Form1'
  ClientHeight = 397
  ClientWidth = 676
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object MPHexEditorEx1: TMPHexEditorEx
    Left = 0
    Top = 0
    Width = 676
    Height = 397
    Cursor = crIBeam
    BackupExtension = '.bak'
    PrintOptions.MarginLeft = 20
    PrintOptions.MarginTop = 15
    PrintOptions.MarginRight = 25
    PrintOptions.MarginBottom = 25
    PrintOptions.Flags = [pfSelectionBold, pfMonochrome]
    PrintFont.Charset = DEFAULT_CHARSET
    PrintFont.Color = clWindowText
    PrintFont.Height = -15
    PrintFont.Name = 'Courier New'
    PrintFont.Style = []
    Align = alClient
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -15
    Font.Name = 'Courier New'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    BytesPerRow = 16
    BytesPerColumn = 1
    Translation = tkAsIs
    OffsetFormat = '-!10:0x|'
    Colors.Background = clWindow
    Colors.ChangedBackground = 11075583
    Colors.ChangedText = clMaroon
    Colors.CursorFrame = clNavy
    Colors.Offset = clBlack
    Colors.OddColumn = clBlue
    Colors.EvenColumn = clNavy
    Colors.CurrentOffsetBackground = clBtnShadow
    Colors.OffsetBackground = clBtnFace
    Colors.CurrentOffset = clBtnHighlight
    Colors.Grid = clBtnFace
    Colors.NonFocusCursorFrame = clAqua
    Colors.ActiveFieldBackground = clWindow
    FocusFrame = True
    DrawGridLines = False
    Version = 'october 7th, 2010; ?markus stephany, http://launchpad.net/dcr'
    InsertMode = True
    BytesPerBlock = -1
  end
end
